allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
minimumReleaseAgeExclude:
  - cssnano-preset-default@9.1.2
  - cssnano@9.1.2
  - postcss-colormin@9.0.5
  - postcss-convert-values@9.0.6
  - postcss-discard-comments@9.0.5
  - postcss-discard-empty@9.0.5
  - postcss-discard-overridden@9.0.5
  - postcss-merge-longhand@9.1.1
  - postcss-merge-rules@9.0.6
  - postcss-minify-font-values@9.0.5
  - postcss-minify-gradients@9.0.5
  - postcss-minify-params@9.0.5
  - postcss-normalize-charset@9.0.5
  - postcss-normalize-display-values@9.0.5
  - postcss-normalize-positions@9.0.5
  - postcss-normalize-repeat-style@9.0.5
  - postcss-normalize-timing-functions@9.0.5
  - postcss-normalize-url@9.0.5
  - postcss-normalize-whitespace@9.0.5
  - postcss-ordered-values@9.0.5
  - postcss-reduce-initial@9.0.5
  - postcss-unique-selectors@9.0.5
  - sass@1.105.1
  - stylehacks@9.0.6
